branch-defaults:
  default:
    environment: null
    group_suffix: null
  master:
    environment: null
global:
  application_name: elasticbeankstalk-profile-project
  branch: null
  default_ec2_keyname: lami.pem
  default_platform: Tomcat 10 with Corretto 21 running on 64bit Amazon Linux 2023
  default_region: eu-north-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: null
  workspace_type: Application
